### ISSUE TITLE
Checkout block support?

### ISSUE THREAD

**Issue by tchunwei** [RazerMS/Shopping-Cart-Plugins-RazerMS_WooCommerce#48]
Current payment plugin only supported in the class checkout shortcode, any chance to support it in new checkout block for better checkout experience?

**Comment by wankimmy** [comment]
hi @tchunwei , we will enhance the plugin to support new checkout block

**Comment by tchunwei** [comment]
hi @wankimmy , do you have any timeline for this feature on when it will be ready?

**Comment by tchunwei** [comment]
hi @wankimmy , appreciate if you can provide some update on this 🙇

**Comment by tchunwei** [comment]
Hi @wankimmy , we really need this to be ready or else we can't use the new WooCommerce local pickup feature if block checkout is not supported. 

We need to go live our website soon and we can't proceed without this ready. An estimated timeline will be helpful or else we can only switch to other payment provider.

Thank you in advance.

**Comment by TheRealNaery** [comment]
Hi @tchunwei , latest version already available for code block ya.

https://github.com/FiuuPayment/Shopping-Cart-Plugins-Fiuu_WooCommerce/tree/master/WooCommerce/woocommerce_rms_normal

**Comment by tchunwei** [comment]
Awesome, thank a lot for the update, shall try it out!
